- name: Provisioning storage for Powermax
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - connection.yml
    - credentials.yml
    - storagedetails.yml

  vars:
    mv_name: "{{ mv_name }}"
    portgroup_name: "{{ portgroup_name }}"
    hostgroup_name: "{{ hostgroup_name }}"
    sg_name: "{{ sg_name }}"

    input: &uni_connection_vars
      serial_no: "{{ serial_no }}"
      password: "{{ password }}"
      unispherehost: "{{ unispherehost }}"
      universion: "{{ universion }}"
      user: "{{  user  }}"
      verifycert: "{{ verifycert }}"

  tasks:
    - name: Delete MV "{{ mv_name }}" 
      dellemc_powermax_maskingview:
        <<: *uni_connection_vars
        mv_name: "{{ mv_name }}"
        portgroup_name: "{{ portgroup_name }}"
        hostgroup_name: "{{ hostgroup_name }}"
        sg_name: "{{ sg_name }}"
        state: 'absent'
        
    - name: Delete Storage group
      dellemc_powermax_storagegroup:
        <<: *uni_connection_vars
        sg_name: "{{ sg_name }}"
        service_level: "Diamond"
        srp: "SRP_1"
        state: 'absent'
        
    - name: Delete host group "{{ hostgroup_name }}"
      dellemc_powermax_hostgroup:
        <<: *uni_connection_vars
        hostgroup_name: "{{ hostgroup_name }}"
        state: "present"
        hosts:
          - "{{ host1_name }}"
          - "{{ host2_name }}"
        host_state: 'present-in-group'    
        
    - name: Delete host "{{ host_name }}"
      dellemc_powermax_host:
        <<: *uni_connection_vars
        host_name: "{{ host1_name }}"
        initiators: "{{ host1_initiators }}"
        state: 'absent'
        initiator_state: 'present-in-host'
    
    - name: Delete host "{{ host2_name }}"
      dellemc_powermax_host:
        <<: *uni_connection_vars
        host_name: "{{ host2_name }}"
        initiators: "{{ host2_initiators }}"
        state: 'absent'
        initiator_state: 'present-in-host'

    - name: Delete port group "{{ portgroup_name }}"
      dellemc_powermax_portgroup:
        <<: *uni_connection_vars
        portgroup_name: "{{ portgroup_name }}"
        state: "present"
        ports:  "{{ port_list }}"
        port_state: 'present-in-group'




